apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: webhost
spec:
  ports:
    - port: 80
  selector:
    app: webhost
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  labels:
    app: webhost
    uses: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: webhost
    uses: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhost
      tier: frontend
  template:
    metadata:
      labels:
        app: webhost
        tier: frontend
        uses: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            name: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-persistent-storage
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-pv-claim
