apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: webhost
spec:
  ports:
    - port: 80
  selector:
    app: webhost
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: webhost
    uses: gatsby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhost
      tier: frontend
  template:
    metadata:
      labels:
        app: webhost
        tier: frontend
        uses: nginx
    spec:
      containers:
      - image: alexfornuto/demo:latest
        name: gatsby
        ports:
          - containerPort: 80
            name: nginx
